### ISSUE TITLE
Cannot find snake2 package

### ISSUE THREAD

**Issue by YechenZhou** [zw199502/rl_snake_robot#1]
"Snake2" package is mentioned  in "./snake_climb/launch/snake_world.launch " file. But the package cannot be found in this repo. Could you show me this package? Thx.

**Comment by zw199502** [comment]
> "Snake2" package is mentioned in "./snake_climb/launch/snake_world.launch " file. But the package cannot be found in this repo. Could you show me this package? Thx.

Please see the zip file in this project

**Comment by YechenZhou** [comment]
> > "Snake2" package is mentioned in "./snake_climb/launch/snake_world.launch " file. But the package cannot be found in this repo. Could you show me this package? Thx.
> 
> Please see the zip file in this project

Sorry. I unpack the snake_climb.tar.gz file, and I still can't find Snake2 package.

**Comment by zw199502** [comment]
> > > "Snake2" package is mentioned in "./snake_climb/launch/snake_world.launch " file. But the package cannot be found in this repo. Could you show me this package? Thx.
> > 
> > 
> > Please see the zip file in this project
> 
> Sorry. I unpack the snake_climb.tar.gz file, and I still can't find Snake2 package.

Snake2 package equals to 'snake_climb' package.

**Comment by YechenZhou** [comment]
Ok, thanks.
